### ISSUE TITLE
Bug: scorll area will block input event listener on items behind it?

### ISSUE THREAD

**Issue by littlee** [trueicecold/phaser-scrollable#7] opened 2018-01-11 10:09 UTC
I have a popup rank view which using this library, and I have a button to toggle this rank view by changing its visible property.

I add onInputDown listener to my whole background image,  and after I show the rank view and hide it, click on the background inside the area where the scroll-area was will not response.

after show and hide my rank view, click inside the red area will not work, but ouside the red area will
![_20180111174955](https://user-images.githubusercontent.com/7534668/34819942-2628f2ac-f6fa-11e7-997e-3d4515f67105.png)

area with red border is my scroll area
![_20180111174912](https://user-images.githubusercontent.com/7534668/34819951-2b2a1880-f6fa-11e7-8fdb-c625418266af.png)

I tried to call .stop method when I hide the rank view, still not work
I tried to call destroy method with my rank view (Phaser.Group) , still not work

**Comment by trueicecold** [comment] 2018-01-14 09:59
Duplicate of #2

**Closed by trueicecold** 2018-01-14 09:59 UTC
